### PR TITLE
Feature/support Clique mulitple sealers

### PR DESCRIPTION
**Pull request by trmaphi**

### CODE REVIEW

**Comment by joshuafernandes** [comment]
Hi @trmaphi thankyou for this submission, we're trying to make sure this works with the quickstart and supports both clients before we can merge. Will keep you posted

**Comment by trmaphi** [comment]
@joshuafernandes I worked on quorum-kubernet repo, I found this inconsistency, hope it helps

**Comment by joshuafernandes** [comment]
Hi @trmaphi I've added #26 which superceedes this PR, Besu and GoQuorum handle clique slightly differently so this should cater to both - could you confirm this works for your use case please before I release this version out?

**Comment by trmaphi** [comment]
@joshuafernandes I worked for my use case, too. Thanks

**Comment by trmaphi** [comment]
Then, I'll close this PR

**Pull request closed without merging**
